/**
 * Webhook Queue Service
 *
 * A thin BullMQ wrapper dedicated to the `webhook-events` queue.
 * The pipeline's QueueService is intentionally left untouched — webhooks
 * have a different job shape and processing lifecycle.
 *
 * Workers that actually process these jobs live outside this file; the route
 * handler only needs to enqueue and return 200 fast.
 */

import { Queue } from 'bullmq';
import { WebhookJobData, WebhookJobResult } from './types';

export const WEBHOOK_QUEUE_NAME = 'webhook-events';

// ---------------------------------------------------------------------------
// Redis connection — shared singleton, lazy-initialised
// ---------------------------------------------------------------------------

function redisConnection() {
  return {
    host: process.env.REDIS_HOST || 'localhost',
    port: parseInt(process.env.REDIS_PORT || '6379', 10),
    password: process.env.REDIS_PASSWORD || undefined,
  };
}

// ---------------------------------------------------------------------------
// WebhookQueueService
// ---------------------------------------------------------------------------

export class WebhookQueueService {
  private queue: Queue<WebhookJobData, WebhookJobResult>;

  constructor() {
    this.queue = new Queue<WebhookJobData, WebhookJobResult>(WEBHOOK_QUEUE_NAME, {
      connection: redisConnection(),
      defaultJobOptions: {
        attempts: 3,
        backoff: { type: 'exponential', delay: 1_000 },
        removeOnComplete: 500,
        removeOnFail: 100,
      },
    });
  }

  /**
   * Add a webhook event to the processing queue.
   *
   * The job name is `<provider>:<event>` which makes it easy to filter in
   * Bull Board / Redis CLI.  The job ID is set to the UUID generated by the
   * route handler so tracing is straightforward.
   *
   * @returns The BullMQ job ID (same as `data.id`).
   */
  async enqueue(data: WebhookJobData): Promise<string> {
    const jobName = `${data.provider}:${data.event}`;
    const job = await this.queue.add(jobName, data, {
      jobId: data.id,
    });
    return job.id ?? data.id;
  }

  /** Gracefully close the queue connection (useful in tests / shutdown). */
  async close(): Promise<void> {
    await this.queue.close();
  }
}
